export const PROGRAMS = [
  {
    id: "backend",
    slug: "backend",
    title: "Backend Engineering",
    description:
      "Master server-side development with modern frameworks, databases, APIs, and cloud infrastructure.",
    icon: "⚙️",
    duration: "9 months",
    level: "Beginner to Advanced",
    color: "from-blue-500 to-blue-700",
    tagline: "Build the systems that power the world.",
    curriculum: [
      "Systems Programming & Linux",
      "Databases: SQL, NoSQL, and Query Optimization",
      "REST & GraphQL API Design",
      "Authentication, Security & Authorization",
      "Microservices Architecture",
      "Message Queues & Event-Driven Systems",
      "Cloud Deployment (AWS/GCP)",
      "Performance Engineering & Observability",
    ],
    projects: [
      "Build a production-grade REST API from scratch",
      "Design a distributed job queue system",
      "Implement a real-time analytics pipeline",
      "Create a scalable microservices architecture",
    ],
    outcomes: [
      "Backend Engineer",
      "API Developer",
      "Systems Architect",
      "Platform Engineer",
    ],
    companies: ["Google", "Andela", "Flutterwave", "Paystack", "AWS"],
    prerequisites: "Basic programming knowledge (any language)",
  },
  {
    id: "fullstack",
    slug: "fullstack",
    title: "Fullstack Development",
    description:
      "Build complete web applications from frontend to backend. React, TypeScript, and production systems.",
    icon: "🌐",
    duration: "12 months",
    level: "Beginner to Advanced",
    color: "from-purple-500 to-purple-700",
    tagline: "End-to-end ownership of what you ship.",
    curriculum: [
      "HTML, CSS & Modern JavaScript",
      "React & TypeScript",
      "State Management & Data Fetching",
      "Next.js & Server-Side Rendering",
      "Node.js & Express Backend",
      "Databases & ORMs",
      "Authentication & Deployment",
      "Testing, CI/CD & DevOps Basics",
    ],
    projects: [
      "Ship a full SaaS application with auth and payments",
      "Build a real-time collaborative tool",
      "Create a production e-commerce platform",
      "Launch a portfolio of deployed web apps",
    ],
    outcomes: [
      "Fullstack Engineer",
      "Frontend Developer",
      "Software Engineer",
      "Tech Lead",
    ],
    companies: ["Meta", "Andela", "Interswitch", "Stripe", "Linear"],
    prerequisites: "No experience required — just commitment",
  },
  {
    id: "ai",
    slug: "ai",
    title: "Artificial Intelligence",
    description:
      "Machine learning, deep learning, and practical AI applications. Build intelligent systems that solve real problems.",
    icon: "🧠",
    duration: "12 months",
    level: "Intermediate",
    color: "from-orange-500 to-orange-700",
    tagline: "From data to decisions, end-to-end.",
    curriculum: [
      "Python for Data Science & Engineering",
      "Statistics & Probability for ML",
      "Supervised & Unsupervised Learning",
      "Neural Networks & Deep Learning",
      "Computer Vision with CNNs",
      "Natural Language Processing",
      "MLOps: Deploying and Serving Models",
      "Applied AI for Real-World Problems",
    ],
    projects: [
      "Train and deploy a crop disease detection model",
      "Build a conversational AI assistant",
      "Create a real-time anomaly detection system",
      "Develop a multimodal AI application",
    ],
    outcomes: [
      "ML Engineer",
      "AI Researcher",
      "Data Scientist",
      "AI Product Developer",
    ],
    companies: ["DeepMind", "Google", "Meta AI", "Microsoft", "OpenAI"],
    prerequisites: "Comfortable with Python and basic math",
  },
  {
    id: "robotics",
    slug: "robotics",
    title: "Robotics Engineering",
    description:
      "Hardware, embedded systems, and robotics. From microcontrollers to autonomous systems.",
    icon: "🤖",
    duration: "12 months",
    level: "Intermediate",
    color: "from-green-500 to-green-700",
    tagline: "Build machines that move and think.",
    curriculum: [
      "Electronics, Sensors & Actuators",
      "Microcontrollers & RTOS",
      "Robot Operating System (ROS)",
      "Computer Vision for Robotics",
      "SLAM & Path Planning",
      "Control Systems & PID",
      "Autonomous Navigation",
      "Mechatronics & System Integration",
    ],
    projects: [
      "Build a line-following autonomous robot",
      "Develop a robotic arm with precision control",
      "Create a SLAM-enabled indoor navigation system",
      "Deploy a multi-sensor environmental bot",
    ],
    outcomes: [
      "Robotics Engineer",
      "Autonomous Systems Developer",
      "Mechatronics Engineer",
      "Research Scientist",
    ],
    companies: ["Boston Dynamics", "Tesla", "DJI", "KUKA", "ABB Robotics"],
    prerequisites: "Basic electronics or programming background helpful",
  },
  {
    id: "embedded",
    slug: "embedded",
    title: "Embedded Systems",
    description:
      "Low-level programming, IoT, and device development. Build systems that power the physical world.",
    icon: "🔌",
    duration: "9 months",
    level: "Intermediate",
    color: "from-yellow-500 to-yellow-700",
    tagline: "Where software meets the physical world.",
    curriculum: [
      "C Programming for Embedded Systems",
      "Microcontroller Architecture (ARM, AVR)",
      "Real-Time Operating Systems (RTOS)",
      "Communication Protocols (SPI, I2C, UART, CAN)",
      "IoT Architecture & Cloud Connectivity",
      "Power Management & Optimization",
      "Firmware Development & Debugging",
      "Device Security & OTA Updates",
    ],
    projects: [
      "Build a smart home automation controller",
      "Design an industrial IoT monitoring device",
      "Create a wearable health sensor platform",
      "Develop a custom RTOS scheduler",
    ],
    outcomes: [
      "Embedded Engineer",
      "Firmware Developer",
      "IoT Engineer",
      "Systems Software Engineer",
    ],
    companies: ["Arm", "STMicroelectronics", "Qualcomm", "Bosch", "Siemens"],
    prerequisites: "Basic programming knowledge",
  },
  {
    id: "cloud",
    slug: "cloud",
    title: "Cloud Engineering",
    description:
      "AWS, GCP, Kubernetes, and infrastructure-as-code. Scale systems to millions of users.",
    icon: "☁️",
    duration: "9 months",
    level: "Intermediate",
    color: "from-cyan-500 to-cyan-700",
    tagline: "Own the infrastructure powering scale.",
    curriculum: [
      "Cloud Fundamentals (AWS & GCP)",
      "Infrastructure as Code (Terraform, Pulumi)",
      "Containers: Docker & Kubernetes",
      "CI/CD Pipelines & GitOps",
      "Networking, VPCs & Security Groups",
      "Serverless Architecture & Functions",
      "Observability: Logs, Metrics, Traces",
      "Cost Optimization & FinOps",
    ],
    projects: [
      "Architect a multi-region, high-availability platform",
      "Build a fully automated CI/CD system",
      "Design and deploy a Kubernetes cluster from scratch",
      "Implement a zero-downtime deployment pipeline",
    ],
    outcomes: [
      "Cloud Engineer",
      "DevOps Engineer",
      "Site Reliability Engineer",
      "Platform Engineer",
    ],
    companies: ["AWS", "GCP", "Microsoft Azure", "Cloudflare", "HashiCorp"],
    prerequisites: "Basic Linux and networking knowledge",
  },
  {
    id: "cybersecurity",
    slug: "cybersecurity",
    title: "Cybersecurity",
    description:
      "Network security, penetration testing, and secure systems design. Protect critical infrastructure.",
    icon: "🔐",
    duration: "9 months",
    level: "Intermediate to Advanced",
    color: "from-red-500 to-red-700",
    tagline: "Attack to understand. Defend to protect.",
    curriculum: [
      "Networking Fundamentals & Protocols",
      "Ethical Hacking & Penetration Testing",
      "Web Application Security (OWASP Top 10)",
      "Cryptography & PKI",
      "Threat Modeling & Risk Assessment",
      "Digital Forensics & Incident Response",
      "Security Operations & SIEM",
      "Secure Software Development Lifecycle",
    ],
    projects: [
      "Conduct a full penetration test on a lab environment",
      "Build a real-time network intrusion detection system",
      "Design a secure authentication architecture",
      "Perform forensic analysis of a compromised system",
    ],
    outcomes: [
      "Security Engineer",
      "Penetration Tester",
      "Security Analyst",
      "CISO (long-term)",
    ],
    companies: ["Google", "CrowdStrike", "Palo Alto Networks", "Darktrace", "IBM Security"],
    prerequisites: "Basic networking and OS knowledge",
  },
  {
    id: "product",
    slug: "product",
    title: "Product Design",
    description:
      "User research, prototyping, and design thinking. Create products that users love.",
    icon: "✨",
    duration: "6 months",
    level: "Beginner to Intermediate",
    color: "from-pink-500 to-pink-700",
    tagline: "Design with empathy. Ship with purpose.",
    curriculum: [
      "Design Thinking & Human-Centered Design",
      "User Research Methods & Interviews",
      "Information Architecture & Wireframing",
      "UI Design Systems & Visual Hierarchy",
      "Figma: Components, Prototyping & Handoff",
      "Usability Testing & Iteration",
      "Product Strategy & Roadmapping",
      "Working with Engineering Teams",
    ],
    projects: [
      "Design a complete mobile app from research to prototype",
      "Redesign an existing product with data-driven decisions",
      "Build and test a design system from scratch",
      "Ship a feature end-to-end in a product team",
    ],
    outcomes: [
      "Product Designer",
      "UX Researcher",
      "UI Designer",
      "Product Manager",
    ],
    companies: ["Linear", "Figma", "Notion", "Paystack", "Interswitch"],
    prerequisites: "No design experience needed",
  },
];
