export const PROGRAMS = [
  {
    id: "mobile-app-development",
    slug: "mobile-app-development",
    title: "Mobile App Development with Flutter",
    description:
      "Learn the fundamentals of Flutter and build engaging native mobile applications for Android and iOS.",
    icon: "📱",
    duration: "3 months",
    fee: "GHC 1200",
    level: "Beginner friendly",
    color: "from-sky-500 to-blue-700",
    tagline:
      "Move from basic ICT confidence to shipping cross-platform mobile applications.",
    curriculum: [
      "Programming fundamentals for mobile development",
      "Dart and Flutter foundations",
      "Cross-platform UI development",
      "State, navigation, and forms",
      "Working with APIs and local storage",
      "Android and iOS app packaging",
    ],
    projects: [
      "Build a polished personal productivity app",
      "Create a data-driven app connected to an API",
      "Prototype and test a community-focused mobile solution",
      "Package a release-ready Android build",
    ],
    outcomes: [
      "Mobile app developer",
      "Flutter developer",
      "Junior software developer",
      "Product prototyper",
    ],
    companies: ["KNUST certificate", "Kumasi Hive network", "Virtual jobs", "Internships"],
    prerequisites: "Basic ICT confidence and commitment to practice",
  },
  {
    id: "digital-marketing",
    slug: "digital-marketing",
    title: "Professional Digital Marketing",
    description:
      "Build a solid foundation in digital marketing and learn how to use modern tools to reach a wider audience.",
    icon: "📣",
    duration: "3 months",
    fee: "GHC 1200",
    level: "Beginner friendly",
    color: "from-orange-500 to-orange-700",
    tagline:
      "Understand audiences, campaigns, channels, and measurable growth.",
    curriculum: [
      "Digital marketing strategy",
      "Audience research and positioning",
      "Social media campaign planning",
      "Search, content, and email marketing",
      "Analytics and performance reporting",
      "Marketing tools for small businesses",
    ],
    projects: [
      "Create a complete campaign plan for a local business",
      "Run a content calendar and reporting workflow",
      "Build a landing page messaging strategy",
      "Present a campaign performance review",
    ],
    outcomes: [
      "Digital marketer",
      "Social media strategist",
      "Growth assistant",
      "Marketing coordinator",
    ],
    companies: ["KNUST certificate", "Kumasi Hive network", "Virtual jobs", "Internships"],
    prerequisites: "No prior marketing experience required",
  },
  {
    id: "iot-wireless-sensor-networks",
    slug: "iot-wireless-sensor-networks",
    title: "IoT and Wireless Sensor Networks",
    description:
      "Explore embedded systems, Raspberry Pi, Arduino, and connected devices that can be controlled remotely.",
    icon: "📡",
    duration: "3 months",
    fee: "GHC 1200",
    level: "Beginner to intermediate",
    color: "from-green-500 to-emerald-700",
    tagline:
      "Connect physical devices to the internet and turn sensor data into useful systems.",
    curriculum: [
      "IoT concepts and connected-device architecture",
      "Sensors, actuators, and microcontrollers",
      "Arduino and Raspberry Pi platforms",
      "Wireless sensor networks",
      "Device control and monitoring",
      "Simple dashboards and remote interaction",
    ],
    projects: [
      "Build a sensor-based monitoring prototype",
      "Connect an Arduino device to a simple dashboard",
      "Create a remote-control workflow for a physical device",
      "Demo an IoT solution for a community problem",
    ],
    outcomes: [
      "IoT technician",
      "Embedded systems learner",
      "Hardware prototyper",
      "Junior innovation associate",
    ],
    companies: ["KNUST certificate", "Kumasi Hive network", "Virtual jobs", "Internships"],
    prerequisites: "Basic computer literacy; electronics curiosity helps",
  },
  {
    id: "modern-computer-science",
    slug: "modern-computer-science",
    title: "Modern Computer Science: IT and Programming",
    description:
      "Learn the building blocks of front-end development, Python programming, algorithms, web development, AI, and Node.js.",
    icon: "💻",
    duration: "3 months",
    fee: "GHC 1200",
    level: "Beginner friendly",
    color: "from-violet-500 to-indigo-700",
    tagline:
      "Build a practical programming foundation for software, web, and emerging technology paths.",
    curriculum: [
      "Front-end development foundations",
      "Python programming basics",
      "Algorithms, data structures, and control structures",
      "HTML, CSS, JavaScript, and web tooling",
      "Introduction to AI and modern technology stacks",
      "Node.js fundamentals and authentication basics",
    ],
    projects: [
      "Build and publish a responsive website",
      "Create Python scripts that solve practical problems",
      "Develop a simple authenticated web app",
      "Present a final software project",
    ],
    outcomes: [
      "Junior developer",
      "IT support associate",
      "Web developer",
      "Programming trainee",
    ],
    companies: ["KNUST certificate", "Kumasi Hive network", "Virtual jobs", "Internships"],
    prerequisites: "No prior programming experience required",
  },
  {
    id: "digital-fabrication",
    slug: "digital-fabrication",
    title: "Digital Fabrication and Manufacturing",
    description:
      "Learn how digital data drives manufacturing equipment to create practical parts and prototypes.",
    icon: "🛠️",
    duration: "3 months",
    fee: "GHC 1200",
    level: "Beginner to intermediate",
    color: "from-amber-500 to-orange-700",
    tagline:
      "Turn design files into physical objects using modern fabrication workflows.",
    curriculum: [
      "AutoCAD 2D foundations",
      "3D modelling with Fusion 360",
      "Additive technology and 3D printing",
      "Subtractive technology",
      "Laser cutting and lathe machining",
      "Design-for-manufacturing practices",
    ],
    projects: [
      "Model and fabricate a functional prototype",
      "Prepare files for 3D printing and laser cutting",
      "Create a small product enclosure",
      "Document a digital fabrication workflow",
    ],
    outcomes: [
      "Digital fabrication assistant",
      "Prototype technician",
      "CAD trainee",
      "Maker-space operator",
    ],
    companies: ["KNUST certificate", "Kumasi Hive network", "Virtual jobs", "Internships"],
    prerequisites: "Comfort using a computer; design experience is helpful",
  },
  {
    id: "business-management",
    slug: "business-management",
    title: "Business Management Essentials",
    description:
      "Understand the pillars of starting a business, finding customers, building trust, and designing a profitable model.",
    icon: "📈",
    duration: "3 months",
    fee: "GHC 1200",
    level: "Beginner friendly",
    color: "from-teal-500 to-cyan-700",
    tagline:
      "Connect technology skills to customers, revenue, and sustainable ventures.",
    curriculum: [
      "Business model fundamentals",
      "Customer discovery and validation",
      "Affordable product development",
      "Marketing and distribution channels",
      "Building trust with customers",
      "Simple financial planning and profitability",
    ],
    projects: [
      "Create a lean business model canvas",
      "Interview and map target customers",
      "Plan a low-cost go-to-market test",
      "Pitch a practical venture concept",
    ],
    outcomes: [
      "Startup founder",
      "Business development assistant",
      "Product associate",
      "Innovation coordinator",
    ],
    companies: ["KNUST certificate", "Kumasi Hive network", "Virtual jobs", "Internships"],
    prerequisites: "No business background required",
  },
];
